// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebsite.Models;

namespace MyWebsite.Migrations
{
    [DbContext(typeof(WebsiteContext))]
    [Migration("20190829051841_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyWebsite.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("MyWebsite.Models.BlogImg", b =>
                {
                    b.Property<int>("BlogImgId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alt");

                    b.Property<int>("BlogId");

                    b.Property<string>("ImgLoc");

                    b.HasKey("BlogImgId");

                    b.HasIndex("BlogId");

                    b.ToTable("BlogImgs");
                });

            modelBuilder.Entity("MyWebsite.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Difficult")
                        .IsRequired();

                    b.Property<string>("LangAndTech")
                        .IsRequired();

                    b.Property<string>("Learned")
                        .IsRequired();

                    b.Property<string>("LiveURL");

                    b.Property<string>("RepoURL");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("MyWebsite.Models.ProjectImg", b =>
                {
                    b.Property<int>("ProjectImgId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alt");

                    b.Property<string>("ImgLoc");

                    b.Property<int>("ProjectId");

                    b.HasKey("ProjectImgId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectImgs");
                });

            modelBuilder.Entity("MyWebsite.Models.BlogImg", b =>
                {
                    b.HasOne("MyWebsite.Models.Blog")
                        .WithMany("BlogImgs")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyWebsite.Models.ProjectImg", b =>
                {
                    b.HasOne("MyWebsite.Models.Project")
                        .WithMany("ProjectImgs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
